"""Give the English pages the same hreflang set the translated copies get, and
regenerate sitemap.xml so every locale of every page is listed with its
alternates. Idempotent: run it after adding or removing a language."""
import sys, os, re
sys.path.insert(0, os.path.dirname(__file__))
from i18n_lib import PAGES, LANGS
from i18n_build import url_for, alternates

SITEMAP_PAGES = [p for p in PAGES if p != '404.html']

# 404 carries no canonical and no alternates: it is not a page anyone links to.
for page in SITEMAP_PAGES:
    s = open(page).read()
    s = re.sub(r'(\n[ \t]*<link rel="alternate" hreflang="[^"]*" href="[^"]*" />)+', '', s)
    m = re.search(r'[ \t]*<link rel="canonical"[^>]*/>', s)
    assert m, page
    s = s[:m.end()] + '\n' + alternates(page) + s[m.end():]
    open(page, 'w').write(s)
    print(f'{page:16} hreflang set written')

rows = []
for page in SITEMAP_PAGES:
    for lang in ['en'] + list(LANGS):
        alts = '\n'.join(
            f'    <xhtml:link rel="alternate" hreflang="{l}" href="{url_for(l, page)}" />'
            for l in ['en'] + list(LANGS))
        alts += f'\n    <xhtml:link rel="alternate" hreflang="x-default" href="{url_for("en", page)}" />'
        rows.append(f'  <url>\n    <loc>{url_for(lang, page)}</loc>\n{alts}\n  </url>')

sitemap = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!-- Generated by tools/i18n_heads.py — do not edit by hand. Every page is\n'
           '     listed once per language, and each entry carries the full alternate set\n'
           '     so a crawler that finds any one of them finds the other four. -->\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
           '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
           + '\n'.join(rows) + '\n</urlset>\n')
open('sitemap.xml', 'w').write(sitemap)
print(f'sitemap.xml: {len(rows)} urls ({len(SITEMAP_PAGES)} pages x {1+len(LANGS)} languages)')
